// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAX7eTJg5YPL2CH-GfPU7Dv-2iWy_vef68',
    appId: '1:434298692437:web:a4b7a3c2d061393a2785dc',
    messagingSenderId: '434298692437',
    projectId: 'flowchat-cc136',
    authDomain: 'flowchat-cc136.firebaseapp.com',
    storageBucket: 'flowchat-cc136.firebasestorage.app',
    measurementId: 'G-HLC2Q63Z7T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjwo4Z9LeeIQ6RFzi4tz7N-YO_1ON9Jxg',
    appId: '1:434298692437:android:a06001183e6ce79c2785dc',
    messagingSenderId: '434298692437',
    projectId: 'flowchat-cc136',
    storageBucket: 'flowchat-cc136.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkyzPnw4NpIMLqygS1kJm3QKf-_N-OOnU',
    appId: '1:434298692437:ios:7ba1b68f11bb21882785dc',
    messagingSenderId: '434298692437',
    projectId: 'flowchat-cc136',
    storageBucket: 'flowchat-cc136.firebasestorage.app',
    iosBundleId: 'com.example.flowChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkyzPnw4NpIMLqygS1kJm3QKf-_N-OOnU',
    appId: '1:434298692437:ios:7ba1b68f11bb21882785dc',
    messagingSenderId: '434298692437',
    projectId: 'flowchat-cc136',
    storageBucket: 'flowchat-cc136.firebasestorage.app',
    iosBundleId: 'com.example.flowChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAX7eTJg5YPL2CH-GfPU7Dv-2iWy_vef68',
    appId: '1:434298692437:web:29e7387a76e510482785dc',
    messagingSenderId: '434298692437',
    projectId: 'flowchat-cc136',
    authDomain: 'flowchat-cc136.firebaseapp.com',
    storageBucket: 'flowchat-cc136.firebasestorage.app',
    measurementId: 'G-8MYDKPMQBF',
  );
}
